# Uncomment the next line to define a global platform for your project
# platform :ios, '10'

target 'editorTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for editorTest
  pod ''
  pod 'iOSPhotoEditor', :git => 'https://github.com/goreste/photo-editor.git', :branch => 'master'

end
