# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
  pod 'PhotoEditor', :git => 'https://github.com/goreste/photo-editor.git', :tag => '0.8.2'
end
